export const RECEIVE_LOADING_STATUS = 'RECEIVE_LOADING_STATUS';
export const RECEIVE_HOIST_CAM_DIRECTOR_IMAGES = 'RECEIVE_HOIST_CAM_DIRECTOR_IMAGES';
export const RECEIVE_PROCESSING_OPTIONS = 'RECEIVE_PROCESSING_OPTIONS';
export const RECEIVE_DELIVERY_OPTIONS = 'RECEIVE_DELIVERY_OPTIONS';
export const RECEIVE_SELECTED_HOIST_CAM_DIRECTOR_IMAGES = 'RECEIVE_SELECTED_HOIST_CAM_DIRECTOR_IMAGES';
export const RECEIVE_SELECTED_PROCESSING_OPTIONS = 'RECEIVE_SELECTED_PROCESSING_OPTIONS';
export const RECEIVE_SELECTED_DELIVERY_OPTIONS = 'RECEIVE_SELECTED_DELIVERY_OPTIONS';
